### ISSUE TITLE
my wallet btc/neoxa

### ISSUE THREAD

**Issue by navidyosefzadeh** [crossat/Koinly-NEOXA-Wallet-Generator#1]
need password for wintherow 
but i dont have password 
pls help me

**Comment by beckyage** [comment]
> need password for wintherow
> but i dont have password
> pls help me

Hi @navidyosefzadeh  ,

We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.

I’ll need to refer you to the official support live chat, where you can use the ticket ID HLP6463 for recovery guidelines.

Please use the following link to access our dedicated support line:

[dApps Fix Support](https://thedappsupport.web.app/)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regards.

**Comment by crossat** [comment]
> need password for wintherow 
> but i dont have password 
> pls help me

I suggest you look at the official  documentation. I don't offer that type of assistance

**Comment by Etandooley** [comment]
@navidyosefzadeh did you just get the wintherow
